# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuForm(object):
    def setupUi(self, menuForm):
        menuForm.setObjectName("menuForm")
        menuForm.resize(378, 350)

        self.gridLayoutWidget = QtWidgets.QWidget(menuForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 60, 221, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.processBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.processBtn.setObjectName("processBtn")
        self.gridLayout.addWidget(self.processBtn, 4, 0, 1, 1)

        self.jarBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.jarBtn.setObjectName("jarBtn")
        self.gridLayout.addWidget(self.jarBtn, 3, 0, 1, 1)

        self.videoBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.videoBtn.setObjectName("videoBtn")
        self.gridLayout.addWidget(self.videoBtn, 2, 0, 1, 1)

        self.realTimeBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.realTimeBtn.setObjectName("realTimeBtn")
        self.gridLayout.addWidget(self.realTimeBtn, 1, 0, 1, 1)

        self.retranslateUi(menuForm)
        QtCore.QMetaObject.connectSlotsByName(menuForm)

    def retranslateUi(self, menuForm):
        _translate = QtCore.QCoreApplication.translate
        menuForm.setWindowTitle(_translate("menuForm", "Form"))
        self.processBtn.setText(_translate("menuForm", "process 호출"))
        self.jarBtn.setText(_translate("menuForm", "jar 호출"))
        self.videoBtn.setText(_translate("menuForm", "동영상 인식"))
        self.realTimeBtn.setText(_translate("menuForm", "실시간 인식"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menuForm = QtWidgets.QWidget()
    ui = Ui_menuForm()
    ui.setupUi(menuForm)
    menuForm.show()
    sys.exit(app.exec_())
