"""login Ui
기능설명:
    로그인 UI 틀을 나타내는 코드임. QTDesigner에서 작성하여 파이썬 코드로 변환하였음.
개발자:
    송재임
개발일시:
    2021.01.02.14.00.00
버전:
    0.0.1
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# PyQT Designer에서 기본적으로 import하는 것들
# QtWidgets은 PyQT5에서 모든 UI 객체를 포함하고 있는 클래스라서 무조건 import
from PyQt5 import QtCore, QtGui, QtWidgets


class UiDialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(388, 228)
        self.label_username = QtWidgets.QLabel(dialog)
        self.label_username.setGeometry(QtCore.QRect(70, 79, 91, 21))

        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_username.setFont(font)
        self.label_username.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_username.setObjectName("label_username")

        self.label_password = QtWidgets.QLabel(dialog)
        self.label_password.setGeometry(QtCore.QRect(70, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")

        self.lineEdit_username = QtWidgets.QLineEdit(dialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(170, 80, 141, 21))
        self.lineEdit_username.setObjectName("lineEdit_username")

        self.lineEdit_password = QtWidgets.QLineEdit(dialog)
        self.lineEdit_password.setGeometry(QtCore.QRect(170, 110, 141, 21))
        self.lineEdit_password.setObjectName("lineEdit_password")

        self.btn_login = QtWidgets.QPushButton(dialog)
        self.btn_login.setGeometry(QtCore.QRect(150, 150, 93, 28))
        self.btn_login.setObjectName("btn_login")

        self.label_title = QtWidgets.QLabel(dialog)
        self.label_title.setGeometry(QtCore.QRect(140, 20, 81, 31))

        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Login"))
        self.label_username.setText(_translate("dialog", "사용자 이름"))
        self.label_password.setText(_translate("dialog", "비밀번호"))
        self.btn_login.setText(_translate("dialog", "로그인"))
        self.label_title.setText(_translate("dialog", "Login"))


if __name__ == "__main__":
    import sys

    # 모든 PyQT Application들은 항상 Application Object를 생성해야 함
    app = QtWidgets.QApplication(sys.argv)
    # QtWidgets은 UI를 구성해주는 클래스들을 포함하고 있음
    # 해당 소스는 Diaglog임으로 QtWidgest의 QDialog 메소드 호출
    dialog = QtWidgets.QDialog()
    # 위에서 정의한 UI Form을 Form 객체에 적용하고 있음
    ui = UiDialog()
    ui.setupUi(dialog)

    dialog.show()
    sys.exit(app.exec_())
